---

- name: Install AWS CLI tools
  become: yes
  apt: 
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
    - awscli
    - python-pip


- name: Install boto 
  become: yes
  pip: 
    name: boto

