# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push (merges are pushes)
  push:
    # Only triggers on pushes to the main branch
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Define a job to deploy our app
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Define the steps for this workflow
    steps: 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Execute instance refresh
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name whisky-asg
